#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 85
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 11

enum ts_symbol_identifiers {
  anon_sym_LBRACE_LBRACE = 1,
  anon_sym_RBRACE_RBRACE = 2,
  aux_sym_text_token1 = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  sym_conversion = 6,
  anon_sym_DOT = 7,
  anon_sym_LBRACK = 8,
  anon_sym_RBRACK = 9,
  anon_sym_COLON = 10,
  anon_sym_LT = 11,
  anon_sym_GT = 12,
  anon_sym_EQ = 13,
  anon_sym_CARET = 14,
  aux_sym_align_token1 = 15,
  anon_sym_z = 16,
  anon_sym_POUND = 17,
  aux_sym_align_token2 = 18,
  aux_sym_align_token3 = 19,
  aux_sym_align_token4 = 20,
  aux_sym_align_token5 = 21,
  anon_sym_STAR = 22,
  aux_sym_type_token1 = 23,
  anon_sym_DOLLAR = 24,
  sym_identifier = 25,
  sym_item_string = 26,
  sym_text = 27,
  sym_replacement = 28,
  sym_attribute_expression = 29,
  sym_item_expression = 30,
  sym__expression = 31,
  sym_format_spec = 32,
  sym_align = 33,
  sym_sign = 34,
  sym_zero_normalization = 35,
  sym_alternate_form = 36,
  sym_width = 37,
  sym_grouping_option = 38,
  sym_precision = 39,
  sym_type = 40,
  sym__count = 41,
  sym_parameter = 42,
  sym_integer = 43,
  aux_sym_text_repeat1 = 44,
  aux_sym_integer_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [aux_sym_text_token1] = "text_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_conversion] = "conversion",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_EQ] = "=",
  [anon_sym_CARET] = "^",
  [aux_sym_align_token1] = "align_token1",
  [anon_sym_z] = "z",
  [anon_sym_POUND] = "#",
  [aux_sym_align_token2] = "align_token2",
  [aux_sym_align_token3] = "align_token3",
  [aux_sym_align_token4] = "align_token4",
  [aux_sym_align_token5] = "character",
  [anon_sym_STAR] = "*",
  [aux_sym_type_token1] = "type_token1",
  [anon_sym_DOLLAR] = "$",
  [sym_identifier] = "identifier",
  [sym_item_string] = "item_string",
  [sym_text] = "text",
  [sym_replacement] = "replacement",
  [sym_attribute_expression] = "attribute_expression",
  [sym_item_expression] = "item_expression",
  [sym__expression] = "_expression",
  [sym_format_spec] = "format_spec",
  [sym_align] = "align",
  [sym_sign] = "sign",
  [sym_zero_normalization] = "zero_normalization",
  [sym_alternate_form] = "alternate_form",
  [sym_width] = "width",
  [sym_grouping_option] = "grouping_option",
  [sym_precision] = "precision",
  [sym_type] = "type",
  [sym__count] = "_count",
  [sym_parameter] = "parameter",
  [sym_integer] = "integer",
  [aux_sym_text_repeat1] = "text_repeat1",
  [aux_sym_integer_repeat1] = "integer_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [aux_sym_text_token1] = aux_sym_text_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_conversion] = sym_conversion,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_CARET] = anon_sym_CARET,
  [aux_sym_align_token1] = aux_sym_align_token1,
  [anon_sym_z] = anon_sym_z,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_align_token2] = aux_sym_align_token2,
  [aux_sym_align_token3] = aux_sym_align_token3,
  [aux_sym_align_token4] = aux_sym_align_token4,
  [aux_sym_align_token5] = aux_sym_align_token5,
  [anon_sym_STAR] = anon_sym_STAR,
  [aux_sym_type_token1] = aux_sym_type_token1,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_identifier] = sym_identifier,
  [sym_item_string] = sym_item_string,
  [sym_text] = sym_text,
  [sym_replacement] = sym_replacement,
  [sym_attribute_expression] = sym_attribute_expression,
  [sym_item_expression] = sym_item_expression,
  [sym__expression] = sym__expression,
  [sym_format_spec] = sym_format_spec,
  [sym_align] = sym_align,
  [sym_sign] = sym_sign,
  [sym_zero_normalization] = sym_zero_normalization,
  [sym_alternate_form] = sym_alternate_form,
  [sym_width] = sym_width,
  [sym_grouping_option] = sym_grouping_option,
  [sym_precision] = sym_precision,
  [sym_type] = sym_type,
  [sym__count] = sym__count,
  [sym_parameter] = sym_parameter,
  [sym_integer] = sym_integer,
  [aux_sym_text_repeat1] = aux_sym_text_repeat1,
  [aux_sym_integer_repeat1] = aux_sym_integer_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_conversion] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_align_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_z] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_align_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_align_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_align_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_align_token5] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_type_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_item_string] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_replacement] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_item_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_format_spec] = {
    .visible = true,
    .named = true,
  },
  [sym_align] = {
    .visible = true,
    .named = true,
  },
  [sym_sign] = {
    .visible = true,
    .named = true,
  },
  [sym_zero_normalization] = {
    .visible = true,
    .named = true,
  },
  [sym_alternate_form] = {
    .visible = true,
    .named = true,
  },
  [sym_width] = {
    .visible = true,
    .named = true,
  },
  [sym_grouping_option] = {
    .visible = true,
    .named = true,
  },
  [sym_precision] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym__count] = {
    .visible = false,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_attribute = 2,
  field_conversion = 3,
  field_fill = 4,
  field_format = 5,
  field_item = 6,
  field_object = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_attribute] = "attribute",
  [field_conversion] = "conversion",
  [field_fill] = "fill",
  [field_format] = "format",
  [field_item] = "item",
  [field_object] = "object",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 2},
  [9] = {.index = 12, .length = 3},
  [10] = {.index = 15, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_conversion, 1},
  [1] =
    {field_argument, 1},
  [2] =
    {field_format, 1},
  [3] =
    {field_conversion, 1},
    {field_format, 2},
  [5] =
    {field_fill, 0},
  [6] =
    {field_argument, 1},
    {field_conversion, 2},
  [8] =
    {field_attribute, 2},
    {field_object, 0},
  [10] =
    {field_argument, 1},
    {field_format, 2},
  [12] =
    {field_argument, 1},
    {field_conversion, 2},
    {field_format, 3},
  [15] =
    {field_item, 2},
    {field_object, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [5] = {
    [0] = aux_sym_align_token5,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '!', 37,
        '#', 27,
        '$', 41,
        '*', 39,
        ',', 30,
        '.', 17,
        ':', 20,
        '<', 21,
        '=', 23,
        '>', 22,
        '[', 18,
        ']', 19,
        '^', 24,
        '_', 31,
        'z', 26,
        '{', 14,
        '}', 15,
        '%', 32,
        '?', 32,
        'X', 34,
        'x', 34,
        ' ', 25,
        '+', 25,
        '-', 25,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('E' <= lookahead && lookahead <= 'G') ||
          ('b' <= lookahead && lookahead <= 'g') ||
          ('n' <= lookahead && lookahead <= 'p') ||
          lookahead == 's') ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(38);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 7,
        '#', 27,
        '$', 41,
        ',', 30,
        '.', 17,
        ':', 20,
        '<', 21,
        '=', 23,
        '>', 22,
        '[', 18,
        ']', 19,
        '^', 24,
        '_', 31,
        'z', 26,
        '}', 15,
        '%', 32,
        '?', 32,
        'X', 34,
        'x', 34,
        ' ', 25,
        '+', 25,
        '-', 25,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('E' <= lookahead && lookahead <= 'G') ||
          ('b' <= lookahead && lookahead <= 'g') ||
          ('n' <= lookahead && lookahead <= 'p') ||
          lookahead == 's') ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(42);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 7,
        '$', 41,
        '.', 17,
        ':', 20,
        '<', 21,
        '=', 23,
        '>', 22,
        '[', 18,
        ']', 19,
        '^', 24,
        '}', 15,
        ',', 30,
        '_', 30,
        'X', 33,
        'x', 33,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead == '%' ||
          lookahead == '?' ||
          ('E' <= lookahead && lookahead <= 'G') ||
          ('b' <= lookahead && lookahead <= 'g') ||
          ('n' <= lookahead && lookahead <= 'p') ||
          lookahead == 's') ADVANCE(32);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(7);
      if (lookahead == '*') ADVANCE(39);
      if (lookahead == ':') ADVANCE(20);
      if (lookahead == '}') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '#', 27,
        ',', 30,
        '.', 17,
        '<', 21,
        '=', 23,
        '>', 22,
        '^', 24,
        '_', 31,
        'z', 26,
        '}', 15,
        '%', 32,
        '?', 32,
        'X', 34,
        'x', 34,
        ' ', 25,
        '+', 25,
        '-', 25,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('E' <= lookahead && lookahead <= 'G') ||
          ('b' <= lookahead && lookahead <= 'g') ||
          ('n' <= lookahead && lookahead <= 'p') ||
          lookahead == 's') ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(38);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(36);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '#', 27,
        ',', 30,
        '.', 17,
        '<', 21,
        '=', 23,
        '>', 22,
        '^', 24,
        '_', 31,
        '}', 15,
        '%', 32,
        '?', 32,
        'X', 34,
        'x', 34,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('E' <= lookahead && lookahead <= 'G') ||
          ('b' <= lookahead && lookahead <= 'g') ||
          ('n' <= lookahead && lookahead <= 'p') ||
          lookahead == 's') ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 6:
      if (lookahead == '}') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 'a' ||
          lookahead == 'r' ||
          lookahead == 's') ADVANCE(16);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(43);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '{') ADVANCE(14);
      if (lookahead == '}') ADVANCE(6);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(11);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_conversion);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_align_token1);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_z);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_align_token2);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_align_token2);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(43);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_align_token3);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_align_token3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_align_token4);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_align_token4);
      if (lookahead == '?') ADVANCE(40);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_align_token4);
      if (lookahead == '?') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_align_token4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_align_token5);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_align_token5);
      if (lookahead == 'a' ||
          lookahead == 'r' ||
          lookahead == 's') ADVANCE(16);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_align_token5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_type_token1);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_item_string);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(43);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 9},
  [44] = {.lex_state = 9},
  [45] = {.lex_state = 9},
  [46] = {.lex_state = 9},
  [47] = {.lex_state = 9},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 9},
  [51] = {.lex_state = 9},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 9},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 8},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_conversion] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [aux_sym_align_token1] = ACTIONS(1),
    [anon_sym_z] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [aux_sym_align_token2] = ACTIONS(1),
    [aux_sym_align_token3] = ACTIONS(1),
    [aux_sym_align_token4] = ACTIONS(1),
    [aux_sym_align_token5] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [aux_sym_type_token1] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [1] = {
    [sym_text] = STATE(71),
    [sym_replacement] = STATE(30),
    [aux_sym_text_repeat1] = STATE(30),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(5),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(5),
    [aux_sym_text_token1] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
  },
  [2] = {
    [sym_align] = STATE(3),
    [sym_sign] = STATE(4),
    [sym_zero_normalization] = STATE(6),
    [sym_alternate_form] = STATE(10),
    [sym_width] = STATE(24),
    [sym_grouping_option] = STATE(34),
    [sym_precision] = STATE(64),
    [sym_type] = STATE(76),
    [sym__count] = STATE(42),
    [sym_parameter] = STATE(42),
    [sym_integer] = STATE(35),
    [aux_sym_integer_repeat1] = STATE(15),
    [anon_sym_RBRACE] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_CARET] = ACTIONS(13),
    [aux_sym_align_token1] = ACTIONS(15),
    [anon_sym_z] = ACTIONS(17),
    [anon_sym_POUND] = ACTIONS(19),
    [aux_sym_align_token2] = ACTIONS(21),
    [aux_sym_align_token3] = ACTIONS(23),
    [aux_sym_align_token4] = ACTIONS(25),
    [aux_sym_align_token5] = ACTIONS(27),
    [aux_sym_type_token1] = ACTIONS(29),
    [sym_identifier] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 20,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 1,
      aux_sym_align_token1,
    ACTIONS(37), 1,
      anon_sym_z,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      aux_sym_align_token2,
    ACTIONS(43), 1,
      aux_sym_align_token3,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    STATE(5), 1,
      sym_sign,
    STATE(7), 1,
      sym_zero_normalization,
    STATE(9), 1,
      sym_alternate_form,
    STATE(15), 1,
      aux_sym_integer_repeat1,
    STATE(26), 1,
      sym_width,
    STATE(35), 1,
      sym_integer,
    STATE(37), 1,
      sym_grouping_option,
    STATE(62), 1,
      sym_precision,
    STATE(73), 1,
      sym_type,
    STATE(42), 2,
      sym__count,
      sym_parameter,
  [62] = 18,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(37), 1,
      anon_sym_z,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      aux_sym_align_token2,
    ACTIONS(43), 1,
      aux_sym_align_token3,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    STATE(7), 1,
      sym_zero_normalization,
    STATE(9), 1,
      sym_alternate_form,
    STATE(15), 1,
      aux_sym_integer_repeat1,
    STATE(26), 1,
      sym_width,
    STATE(35), 1,
      sym_integer,
    STATE(37), 1,
      sym_grouping_option,
    STATE(62), 1,
      sym_precision,
    STATE(73), 1,
      sym_type,
    STATE(42), 2,
      sym__count,
      sym_parameter,
  [118] = 18,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_z,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      aux_sym_align_token2,
    ACTIONS(43), 1,
      aux_sym_align_token3,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym_zero_normalization,
    STATE(11), 1,
      sym_alternate_form,
    STATE(15), 1,
      aux_sym_integer_repeat1,
    STATE(27), 1,
      sym_width,
    STATE(35), 1,
      sym_integer,
    STATE(38), 1,
      sym_grouping_option,
    STATE(57), 1,
      sym_precision,
    STATE(72), 1,
      sym_type,
    STATE(42), 2,
      sym__count,
      sym_parameter,
  [174] = 16,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      aux_sym_align_token2,
    ACTIONS(43), 1,
      aux_sym_align_token3,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    STATE(9), 1,
      sym_alternate_form,
    STATE(15), 1,
      aux_sym_integer_repeat1,
    STATE(26), 1,
      sym_width,
    STATE(35), 1,
      sym_integer,
    STATE(37), 1,
      sym_grouping_option,
    STATE(62), 1,
      sym_precision,
    STATE(73), 1,
      sym_type,
    STATE(42), 2,
      sym__count,
      sym_parameter,
  [224] = 16,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      aux_sym_align_token2,
    ACTIONS(43), 1,
      aux_sym_align_token3,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(11), 1,
      sym_alternate_form,
    STATE(15), 1,
      aux_sym_integer_repeat1,
    STATE(27), 1,
      sym_width,
    STATE(35), 1,
      sym_integer,
    STATE(38), 1,
      sym_grouping_option,
    STATE(57), 1,
      sym_precision,
    STATE(72), 1,
      sym_type,
    STATE(42), 2,
      sym__count,
      sym_parameter,
  [274] = 16,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      aux_sym_align_token2,
    ACTIONS(43), 1,
      aux_sym_align_token3,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      sym_alternate_form,
    STATE(15), 1,
      aux_sym_integer_repeat1,
    STATE(28), 1,
      sym_width,
    STATE(35), 1,
      sym_integer,
    STATE(39), 1,
      sym_grouping_option,
    STATE(55), 1,
      sym_precision,
    STATE(75), 1,
      sym_type,
    STATE(42), 2,
      sym__count,
      sym_parameter,
  [324] = 14,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(41), 1,
      aux_sym_align_token2,
    ACTIONS(43), 1,
      aux_sym_align_token3,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_integer_repeat1,
    STATE(27), 1,
      sym_width,
    STATE(35), 1,
      sym_integer,
    STATE(38), 1,
      sym_grouping_option,
    STATE(57), 1,
      sym_precision,
    STATE(72), 1,
      sym_type,
    STATE(42), 2,
      sym__count,
      sym_parameter,
  [368] = 14,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(41), 1,
      aux_sym_align_token2,
    ACTIONS(43), 1,
      aux_sym_align_token3,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    STATE(15), 1,
      aux_sym_integer_repeat1,
    STATE(26), 1,
      sym_width,
    STATE(35), 1,
      sym_integer,
    STATE(37), 1,
      sym_grouping_option,
    STATE(62), 1,
      sym_precision,
    STATE(73), 1,
      sym_type,
    STATE(42), 2,
      sym__count,
      sym_parameter,
  [412] = 14,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(41), 1,
      aux_sym_align_token2,
    ACTIONS(43), 1,
      aux_sym_align_token3,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_integer_repeat1,
    STATE(28), 1,
      sym_width,
    STATE(35), 1,
      sym_integer,
    STATE(39), 1,
      sym_grouping_option,
    STATE(55), 1,
      sym_precision,
    STATE(75), 1,
      sym_type,
    STATE(42), 2,
      sym__count,
      sym_parameter,
  [456] = 14,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(41), 1,
      aux_sym_align_token2,
    ACTIONS(43), 1,
      aux_sym_align_token3,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_integer_repeat1,
    STATE(29), 1,
      sym_width,
    STATE(35), 1,
      sym_integer,
    STATE(40), 1,
      sym_grouping_option,
    STATE(63), 1,
      sym_precision,
    STATE(78), 1,
      sym_type,
    STATE(42), 2,
      sym__count,
      sym_parameter,
  [500] = 3,
    ACTIONS(55), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
    ACTIONS(57), 4,
      anon_sym_z,
      aux_sym_align_token3,
      aux_sym_align_token4,
      sym_identifier,
    ACTIONS(53), 6,
      anon_sym_RBRACE,
      anon_sym_DOT,
      aux_sym_align_token1,
      anon_sym_POUND,
      aux_sym_align_token2,
      aux_sym_type_token1,
  [521] = 3,
    ACTIONS(55), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
    ACTIONS(61), 4,
      anon_sym_z,
      aux_sym_align_token3,
      aux_sym_align_token4,
      sym_identifier,
    ACTIONS(59), 5,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_POUND,
      aux_sym_align_token2,
      aux_sym_type_token1,
  [541] = 4,
    ACTIONS(65), 1,
      aux_sym_align_token2,
    ACTIONS(67), 1,
      aux_sym_align_token4,
    STATE(17), 1,
      aux_sym_integer_repeat1,
    ACTIONS(63), 9,
      anon_sym_RBRACE,
      sym_conversion,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      aux_sym_align_token3,
      aux_sym_type_token1,
      anon_sym_DOLLAR,
  [562] = 3,
    ACTIONS(71), 3,
      aux_sym_align_token3,
      aux_sym_align_token4,
      sym_identifier,
    ACTIONS(55), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
    ACTIONS(69), 5,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_POUND,
      aux_sym_align_token2,
      aux_sym_type_token1,
  [581] = 4,
    ACTIONS(75), 1,
      aux_sym_align_token2,
    ACTIONS(78), 1,
      aux_sym_align_token4,
    STATE(17), 1,
      aux_sym_integer_repeat1,
    ACTIONS(73), 9,
      anon_sym_RBRACE,
      sym_conversion,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      aux_sym_align_token3,
      aux_sym_type_token1,
      anon_sym_DOLLAR,
  [602] = 8,
    ACTIONS(41), 1,
      aux_sym_align_token2,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    ACTIONS(82), 1,
      sym_conversion,
    ACTIONS(84), 1,
      anon_sym_COLON,
    ACTIONS(86), 1,
      sym_identifier,
    STATE(15), 1,
      aux_sym_integer_repeat1,
    STATE(80), 1,
      sym_format_spec,
    STATE(36), 4,
      sym_attribute_expression,
      sym_item_expression,
      sym__expression,
      sym_integer,
  [630] = 3,
    ACTIONS(90), 3,
      aux_sym_align_token3,
      aux_sym_align_token4,
      sym_identifier,
    ACTIONS(55), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
    ACTIONS(88), 4,
      anon_sym_RBRACE,
      anon_sym_DOT,
      aux_sym_align_token2,
      aux_sym_type_token1,
  [648] = 3,
    ACTIONS(94), 1,
      aux_sym_align_token4,
    ACTIONS(55), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
    ACTIONS(92), 6,
      anon_sym_RBRACE,
      anon_sym_DOT,
      aux_sym_align_token2,
      aux_sym_align_token3,
      aux_sym_type_token1,
      anon_sym_DOLLAR,
  [666] = 2,
    ACTIONS(98), 4,
      anon_sym_z,
      aux_sym_align_token3,
      aux_sym_align_token4,
      sym_identifier,
    ACTIONS(96), 6,
      anon_sym_RBRACE,
      anon_sym_DOT,
      aux_sym_align_token1,
      anon_sym_POUND,
      aux_sym_align_token2,
      aux_sym_type_token1,
  [681] = 2,
    ACTIONS(61), 4,
      anon_sym_z,
      aux_sym_align_token3,
      aux_sym_align_token4,
      sym_identifier,
    ACTIONS(59), 5,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_POUND,
      aux_sym_align_token2,
      aux_sym_type_token1,
  [695] = 2,
    ACTIONS(71), 3,
      aux_sym_align_token3,
      aux_sym_align_token4,
      sym_identifier,
    ACTIONS(69), 5,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_POUND,
      aux_sym_align_token2,
      aux_sym_type_token1,
  [708] = 8,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(100), 1,
      aux_sym_align_token3,
    STATE(37), 1,
      sym_grouping_option,
    STATE(62), 1,
      sym_precision,
    STATE(73), 1,
      sym_type,
  [733] = 3,
    ACTIONS(104), 1,
      aux_sym_align_token4,
    ACTIONS(102), 3,
      anon_sym_RBRACE,
      anon_sym_DOT,
      aux_sym_type_token1,
    ACTIONS(55), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
  [748] = 8,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    ACTIONS(100), 1,
      aux_sym_align_token3,
    STATE(38), 1,
      sym_grouping_option,
    STATE(57), 1,
      sym_precision,
    STATE(72), 1,
      sym_type,
  [773] = 8,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(100), 1,
      aux_sym_align_token3,
    STATE(39), 1,
      sym_grouping_option,
    STATE(55), 1,
      sym_precision,
    STATE(75), 1,
      sym_type,
  [798] = 8,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    ACTIONS(100), 1,
      aux_sym_align_token3,
    STATE(40), 1,
      sym_grouping_option,
    STATE(63), 1,
      sym_precision,
    STATE(78), 1,
      sym_type,
  [823] = 8,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(100), 1,
      aux_sym_align_token3,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      sym_grouping_option,
    STATE(61), 1,
      sym_precision,
    STATE(81), 1,
      sym_type,
  [848] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
    STATE(31), 2,
      sym_replacement,
      aux_sym_text_repeat1,
    ACTIONS(110), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [864] = 4,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(117), 1,
      anon_sym_LBRACE,
    STATE(31), 2,
      sym_replacement,
      aux_sym_text_repeat1,
    ACTIONS(114), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [880] = 6,
    ACTIONS(41), 1,
      aux_sym_align_token2,
    ACTIONS(120), 1,
      anon_sym_STAR,
    ACTIONS(122), 1,
      sym_identifier,
    STATE(15), 1,
      aux_sym_integer_repeat1,
    STATE(35), 1,
      sym_integer,
    STATE(67), 2,
      sym__count,
      sym_parameter,
  [900] = 2,
    ACTIONS(90), 3,
      aux_sym_align_token3,
      aux_sym_align_token4,
      sym_identifier,
    ACTIONS(88), 4,
      anon_sym_RBRACE,
      anon_sym_DOT,
      aux_sym_align_token2,
      aux_sym_type_token1,
  [912] = 6,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    STATE(62), 1,
      sym_precision,
    STATE(73), 1,
      sym_type,
  [931] = 3,
    ACTIONS(126), 1,
      aux_sym_align_token4,
    ACTIONS(128), 1,
      anon_sym_DOLLAR,
    ACTIONS(124), 4,
      anon_sym_RBRACE,
      anon_sym_DOT,
      aux_sym_align_token3,
      aux_sym_type_token1,
  [944] = 6,
    ACTIONS(84), 1,
      anon_sym_COLON,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
    ACTIONS(132), 1,
      sym_conversion,
    ACTIONS(134), 1,
      anon_sym_DOT,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    STATE(74), 1,
      sym_format_spec,
  [963] = 6,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(57), 1,
      sym_precision,
    STATE(72), 1,
      sym_type,
  [982] = 6,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      sym_precision,
    STATE(75), 1,
      sym_type,
  [1001] = 6,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      sym_precision,
    STATE(78), 1,
      sym_type,
  [1020] = 6,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      sym_precision,
    STATE(81), 1,
      sym_type,
  [1039] = 6,
    ACTIONS(11), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      sym_precision,
    STATE(83), 1,
      sym_type,
  [1058] = 2,
    ACTIONS(142), 1,
      aux_sym_align_token4,
    ACTIONS(140), 4,
      anon_sym_RBRACE,
      anon_sym_DOT,
      aux_sym_align_token3,
      aux_sym_type_token1,
  [1068] = 2,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    ACTIONS(144), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [1078] = 2,
    ACTIONS(150), 1,
      anon_sym_LBRACE,
    ACTIONS(148), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [1088] = 2,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(152), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [1098] = 2,
    ACTIONS(158), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [1108] = 2,
    ACTIONS(162), 1,
      anon_sym_LBRACE,
    ACTIONS(160), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [1118] = 2,
    ACTIONS(166), 1,
      aux_sym_align_token4,
    ACTIONS(164), 4,
      anon_sym_RBRACE,
      anon_sym_DOT,
      aux_sym_align_token3,
      aux_sym_type_token1,
  [1128] = 1,
    ACTIONS(168), 5,
      anon_sym_RBRACE,
      sym_conversion,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_COLON,
  [1136] = 2,
    ACTIONS(172), 1,
      anon_sym_LBRACE,
    ACTIONS(170), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [1146] = 2,
    ACTIONS(176), 1,
      anon_sym_LBRACE,
    ACTIONS(174), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [1156] = 1,
    ACTIONS(178), 5,
      anon_sym_RBRACE,
      sym_conversion,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_COLON,
  [1164] = 2,
    ACTIONS(180), 1,
      anon_sym_RBRACE,
    ACTIONS(55), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
  [1174] = 2,
    ACTIONS(184), 1,
      anon_sym_LBRACE,
    ACTIONS(182), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [1184] = 4,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(78), 1,
      sym_type,
  [1197] = 2,
    ACTIONS(104), 1,
      aux_sym_align_token4,
    ACTIONS(102), 3,
      anon_sym_RBRACE,
      anon_sym_DOT,
      aux_sym_type_token1,
  [1206] = 4,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      sym_type,
  [1219] = 4,
    ACTIONS(186), 1,
      aux_sym_align_token2,
    ACTIONS(188), 1,
      sym_item_string,
    STATE(15), 1,
      aux_sym_integer_repeat1,
    STATE(69), 1,
      sym_integer,
  [1232] = 1,
    ACTIONS(55), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
  [1239] = 4,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    STATE(84), 1,
      sym_type,
  [1252] = 4,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    STATE(83), 1,
      sym_type,
  [1265] = 4,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      sym_type,
  [1278] = 4,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(81), 1,
      sym_type,
  [1291] = 4,
    ACTIONS(29), 1,
      aux_sym_type_token1,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(45), 1,
      aux_sym_align_token4,
    STATE(73), 1,
      sym_type,
  [1304] = 3,
    ACTIONS(84), 1,
      anon_sym_COLON,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
    STATE(79), 1,
      sym_format_spec,
  [1314] = 3,
    ACTIONS(84), 1,
      anon_sym_COLON,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym_format_spec,
  [1324] = 2,
    ACTIONS(198), 1,
      aux_sym_align_token4,
    ACTIONS(196), 2,
      anon_sym_RBRACE,
      aux_sym_type_token1,
  [1332] = 1,
    ACTIONS(200), 1,
      sym_identifier,
  [1336] = 1,
    ACTIONS(202), 1,
      anon_sym_RBRACK,
  [1340] = 1,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
  [1344] = 1,
    ACTIONS(206), 1,
      ts_builtin_sym_end,
  [1348] = 1,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
  [1352] = 1,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
  [1356] = 1,
    ACTIONS(208), 1,
      anon_sym_RBRACE,
  [1360] = 1,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
  [1364] = 1,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
  [1368] = 1,
    ACTIONS(128), 1,
      anon_sym_DOLLAR,
  [1372] = 1,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
  [1376] = 1,
    ACTIONS(210), 1,
      anon_sym_RBRACE,
  [1380] = 1,
    ACTIONS(212), 1,
      anon_sym_RBRACE,
  [1384] = 1,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
  [1388] = 1,
    ACTIONS(180), 1,
      anon_sym_RBRACE,
  [1392] = 1,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
  [1396] = 1,
    ACTIONS(214), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 118,
  [SMALL_STATE(6)] = 174,
  [SMALL_STATE(7)] = 224,
  [SMALL_STATE(8)] = 274,
  [SMALL_STATE(9)] = 324,
  [SMALL_STATE(10)] = 368,
  [SMALL_STATE(11)] = 412,
  [SMALL_STATE(12)] = 456,
  [SMALL_STATE(13)] = 500,
  [SMALL_STATE(14)] = 521,
  [SMALL_STATE(15)] = 541,
  [SMALL_STATE(16)] = 562,
  [SMALL_STATE(17)] = 581,
  [SMALL_STATE(18)] = 602,
  [SMALL_STATE(19)] = 630,
  [SMALL_STATE(20)] = 648,
  [SMALL_STATE(21)] = 666,
  [SMALL_STATE(22)] = 681,
  [SMALL_STATE(23)] = 695,
  [SMALL_STATE(24)] = 708,
  [SMALL_STATE(25)] = 733,
  [SMALL_STATE(26)] = 748,
  [SMALL_STATE(27)] = 773,
  [SMALL_STATE(28)] = 798,
  [SMALL_STATE(29)] = 823,
  [SMALL_STATE(30)] = 848,
  [SMALL_STATE(31)] = 864,
  [SMALL_STATE(32)] = 880,
  [SMALL_STATE(33)] = 900,
  [SMALL_STATE(34)] = 912,
  [SMALL_STATE(35)] = 931,
  [SMALL_STATE(36)] = 944,
  [SMALL_STATE(37)] = 963,
  [SMALL_STATE(38)] = 982,
  [SMALL_STATE(39)] = 1001,
  [SMALL_STATE(40)] = 1020,
  [SMALL_STATE(41)] = 1039,
  [SMALL_STATE(42)] = 1058,
  [SMALL_STATE(43)] = 1068,
  [SMALL_STATE(44)] = 1078,
  [SMALL_STATE(45)] = 1088,
  [SMALL_STATE(46)] = 1098,
  [SMALL_STATE(47)] = 1108,
  [SMALL_STATE(48)] = 1118,
  [SMALL_STATE(49)] = 1128,
  [SMALL_STATE(50)] = 1136,
  [SMALL_STATE(51)] = 1146,
  [SMALL_STATE(52)] = 1156,
  [SMALL_STATE(53)] = 1164,
  [SMALL_STATE(54)] = 1174,
  [SMALL_STATE(55)] = 1184,
  [SMALL_STATE(56)] = 1197,
  [SMALL_STATE(57)] = 1206,
  [SMALL_STATE(58)] = 1219,
  [SMALL_STATE(59)] = 1232,
  [SMALL_STATE(60)] = 1239,
  [SMALL_STATE(61)] = 1252,
  [SMALL_STATE(62)] = 1265,
  [SMALL_STATE(63)] = 1278,
  [SMALL_STATE(64)] = 1291,
  [SMALL_STATE(65)] = 1304,
  [SMALL_STATE(66)] = 1314,
  [SMALL_STATE(67)] = 1324,
  [SMALL_STATE(68)] = 1332,
  [SMALL_STATE(69)] = 1336,
  [SMALL_STATE(70)] = 1340,
  [SMALL_STATE(71)] = 1344,
  [SMALL_STATE(72)] = 1348,
  [SMALL_STATE(73)] = 1352,
  [SMALL_STATE(74)] = 1356,
  [SMALL_STATE(75)] = 1360,
  [SMALL_STATE(76)] = 1364,
  [SMALL_STATE(77)] = 1368,
  [SMALL_STATE(78)] = 1372,
  [SMALL_STATE(79)] = 1376,
  [SMALL_STATE(80)] = 1380,
  [SMALL_STATE(81)] = 1384,
  [SMALL_STATE(82)] = 1388,
  [SMALL_STATE(83)] = 1392,
  [SMALL_STATE(84)] = 1396,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 4, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 5, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_align, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_align, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sign, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sign, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_zero_normalization, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_zero_normalization, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_integer_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_integer_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_integer_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternate_form, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alternate_form, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_integer_repeat1, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_integer_repeat1, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_align, 2, 0, 5),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_align, 2, 0, 5),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping_option, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouping_option, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 6, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__count, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__count, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 7, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_width, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_width, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replacement, 3, 0, 2),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replacement, 3, 0, 2),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replacement, 3, 0, 3),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replacement, 3, 0, 3),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replacement, 3, 0, 1),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replacement, 3, 0, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replacement, 4, 0, 4),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replacement, 4, 0, 4),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replacement, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replacement, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_expression, 3, 0, 7),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replacement, 4, 0, 6),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replacement, 4, 0, 6),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replacement, 5, 0, 9),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replacement, 5, 0, 9),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_expression, 4, 0, 10),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replacement, 4, 0, 8),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replacement, 4, 0, 8),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 8, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_precision, 2, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_precision, 2, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [206] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 9, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_format_string(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
