#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 76
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 11

enum ts_symbol_identifiers {
  anon_sym_LBRACE_LBRACE = 1,
  anon_sym_RBRACE_RBRACE = 2,
  aux_sym_text_token1 = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  sym_conversion = 6,
  anon_sym_DOT = 7,
  anon_sym_LBRACK = 8,
  anon_sym_RBRACK = 9,
  anon_sym_COLON = 10,
  anon_sym_z = 11,
  anon_sym_POUND = 12,
  anon_sym_LT = 13,
  anon_sym_GT = 14,
  anon_sym_EQ = 15,
  anon_sym_CARET = 16,
  aux_sym_align_token1 = 17,
  aux_sym_align_token2 = 18,
  aux_sym_align_token3 = 19,
  aux_sym_align_token4 = 20,
  aux_sym_align_token5 = 21,
  sym_precision = 22,
  sym_identifier = 23,
  sym_item_string = 24,
  sym_text = 25,
  sym_replacement = 26,
  sym_attribute_expression = 27,
  sym_item_expression = 28,
  sym__expression = 29,
  sym_format_spec = 30,
  sym_align = 31,
  sym_sign = 32,
  sym_width = 33,
  sym_grouping_option = 34,
  sym_type = 35,
  sym_integer = 36,
  aux_sym_text_repeat1 = 37,
  aux_sym_width_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [aux_sym_text_token1] = "text_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_conversion] = "conversion",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [anon_sym_z] = "z",
  [anon_sym_POUND] = "#",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_EQ] = "=",
  [anon_sym_CARET] = "^",
  [aux_sym_align_token1] = "align_token1",
  [aux_sym_align_token2] = "align_token2",
  [aux_sym_align_token3] = "align_token3",
  [aux_sym_align_token4] = "align_token4",
  [aux_sym_align_token5] = "character",
  [sym_precision] = "precision",
  [sym_identifier] = "identifier",
  [sym_item_string] = "item_string",
  [sym_text] = "text",
  [sym_replacement] = "replacement",
  [sym_attribute_expression] = "attribute_expression",
  [sym_item_expression] = "item_expression",
  [sym__expression] = "_expression",
  [sym_format_spec] = "format_spec",
  [sym_align] = "align",
  [sym_sign] = "sign",
  [sym_width] = "width",
  [sym_grouping_option] = "grouping_option",
  [sym_type] = "type",
  [sym_integer] = "integer",
  [aux_sym_text_repeat1] = "text_repeat1",
  [aux_sym_width_repeat1] = "width_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [aux_sym_text_token1] = aux_sym_text_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_conversion] = sym_conversion,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_z] = anon_sym_z,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_CARET] = anon_sym_CARET,
  [aux_sym_align_token1] = aux_sym_align_token1,
  [aux_sym_align_token2] = aux_sym_align_token2,
  [aux_sym_align_token3] = aux_sym_align_token3,
  [aux_sym_align_token4] = aux_sym_align_token4,
  [aux_sym_align_token5] = aux_sym_align_token5,
  [sym_precision] = sym_precision,
  [sym_identifier] = sym_identifier,
  [sym_item_string] = sym_item_string,
  [sym_text] = sym_text,
  [sym_replacement] = sym_replacement,
  [sym_attribute_expression] = sym_attribute_expression,
  [sym_item_expression] = sym_item_expression,
  [sym__expression] = sym__expression,
  [sym_format_spec] = sym_format_spec,
  [sym_align] = sym_align,
  [sym_sign] = sym_sign,
  [sym_width] = sym_width,
  [sym_grouping_option] = sym_grouping_option,
  [sym_type] = sym_type,
  [sym_integer] = sym_integer,
  [aux_sym_text_repeat1] = aux_sym_text_repeat1,
  [aux_sym_width_repeat1] = aux_sym_width_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_conversion] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_z] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_align_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_align_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_align_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_align_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_align_token5] = {
    .visible = true,
    .named = true,
  },
  [sym_precision] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_item_string] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_replacement] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_item_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_format_spec] = {
    .visible = true,
    .named = true,
  },
  [sym_align] = {
    .visible = true,
    .named = true,
  },
  [sym_sign] = {
    .visible = true,
    .named = true,
  },
  [sym_width] = {
    .visible = true,
    .named = true,
  },
  [sym_grouping_option] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_width_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_attribute = 2,
  field_conversion = 3,
  field_fill = 4,
  field_format = 5,
  field_item = 6,
  field_object = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_attribute] = "attribute",
  [field_conversion] = "conversion",
  [field_fill] = "fill",
  [field_format] = "format",
  [field_item] = "item",
  [field_object] = "object",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 2},
  [9] = {.index = 12, .length = 3},
  [10] = {.index = 15, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_conversion, 1},
  [1] =
    {field_argument, 1},
  [2] =
    {field_format, 1},
  [3] =
    {field_conversion, 1},
    {field_format, 2},
  [5] =
    {field_fill, 0},
  [6] =
    {field_argument, 1},
    {field_conversion, 2},
  [8] =
    {field_attribute, 2},
    {field_object, 0},
  [10] =
    {field_argument, 1},
    {field_format, 2},
  [12] =
    {field_argument, 1},
    {field_conversion, 2},
    {field_format, 3},
  [15] =
    {field_item, 2},
    {field_object, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [5] = {
    [0] = aux_sym_align_token5,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '!', 32,
        '#', 21,
        '.', 16,
        ':', 19,
        '<', 22,
        '=', 24,
        '>', 23,
        '[', 17,
        ']', 18,
        '^', 25,
        'z', 20,
        '{', 12,
        '}', 13,
        ',', 29,
        '_', 29,
        ' ', 26,
        '+', 26,
        '-', 26,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (lookahead == '%' ||
          ('E' <= lookahead && lookahead <= 'G') ||
          lookahead == 'X' ||
          ('b' <= lookahead && lookahead <= 'g') ||
          lookahead == 'n' ||
          lookahead == 'o' ||
          lookahead == 's' ||
          lookahead == 'x') ADVANCE(30);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 5,
        '.', 16,
        ':', 19,
        '[', 17,
        ']', 18,
        '}', 13,
        ',', 29,
        '_', 29,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (lookahead == '%' ||
          ('E' <= lookahead && lookahead <= 'G') ||
          lookahead == 'X' ||
          ('b' <= lookahead && lookahead <= 'g') ||
          lookahead == 'n' ||
          lookahead == 'o' ||
          lookahead == 's' ||
          lookahead == 'x') ADVANCE(30);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '.') ADVANCE(15);
      if (lookahead == ':') ADVANCE(19);
      if (lookahead == '[') ADVANCE(17);
      if (lookahead == ']') ADVANCE(18);
      if (lookahead == '}') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '#', 21,
        '.', 33,
        '<', 22,
        '=', 24,
        '>', 23,
        '^', 25,
        'z', 20,
        '}', 13,
        ',', 29,
        '_', 29,
        ' ', 26,
        '+', 26,
        '-', 26,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (lookahead == '%' ||
          ('E' <= lookahead && lookahead <= 'G') ||
          lookahead == 'X' ||
          ('b' <= lookahead && lookahead <= 'g') ||
          lookahead == 'n' ||
          lookahead == 'o' ||
          lookahead == 's' ||
          lookahead == 'x') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != 'z' &&
          lookahead != '{') ADVANCE(31);
      END_STATE();
    case 4:
      if (lookahead == '}') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'a' ||
          lookahead == 'r' ||
          lookahead == 's') ADVANCE(14);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(36);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '{') ADVANCE(12);
      if (lookahead == '}') ADVANCE(4);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(9);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_conversion);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_z);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_align_token1);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_align_token2);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_align_token2);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(36);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_align_token3);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_align_token4);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_align_token5);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_align_token5);
      if (lookahead == 'a' ||
          lookahead == 'r' ||
          lookahead == 's') ADVANCE(14);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_align_token5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_precision);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_item_string);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(36);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_conversion] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_z] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [aux_sym_align_token1] = ACTIONS(1),
    [aux_sym_align_token2] = ACTIONS(1),
    [aux_sym_align_token3] = ACTIONS(1),
    [aux_sym_align_token4] = ACTIONS(1),
    [aux_sym_align_token5] = ACTIONS(1),
    [sym_precision] = ACTIONS(1),
  },
  [1] = {
    [sym_text] = STATE(62),
    [sym_replacement] = STATE(20),
    [aux_sym_text_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(5),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(5),
    [aux_sym_text_token1] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(9), 1,
      anon_sym_RBRACE,
    ACTIONS(11), 1,
      anon_sym_z,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(17), 1,
      aux_sym_align_token1,
    ACTIONS(19), 1,
      aux_sym_align_token2,
    ACTIONS(21), 1,
      aux_sym_align_token3,
    ACTIONS(23), 1,
      aux_sym_align_token4,
    ACTIONS(25), 1,
      aux_sym_align_token5,
    ACTIONS(27), 1,
      sym_precision,
    STATE(5), 1,
      sym_align,
    STATE(9), 1,
      sym_sign,
    STATE(24), 1,
      sym_width,
    STATE(26), 1,
      aux_sym_width_repeat1,
    STATE(47), 1,
      sym_grouping_option,
    STATE(69), 1,
      sym_type,
    ACTIONS(15), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
  [52] = 11,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(31), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      aux_sym_align_token2,
    ACTIONS(37), 1,
      aux_sym_align_token3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(41), 1,
      sym_precision,
    STATE(25), 1,
      sym_width,
    STATE(26), 1,
      aux_sym_width_repeat1,
    STATE(42), 1,
      sym_grouping_option,
    STATE(63), 1,
      sym_type,
    ACTIONS(33), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
  [89] = 10,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 1,
      aux_sym_align_token2,
    ACTIONS(37), 1,
      aux_sym_align_token3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(41), 1,
      sym_precision,
    STATE(25), 1,
      sym_width,
    STATE(26), 1,
      aux_sym_width_repeat1,
    STATE(42), 1,
      sym_grouping_option,
    STATE(63), 1,
      sym_type,
    ACTIONS(33), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
  [123] = 13,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(31), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      aux_sym_align_token2,
    ACTIONS(37), 1,
      aux_sym_align_token3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(41), 1,
      sym_precision,
    ACTIONS(43), 1,
      anon_sym_z,
    ACTIONS(45), 1,
      aux_sym_align_token1,
    STATE(11), 1,
      sym_sign,
    STATE(25), 1,
      sym_width,
    STATE(26), 1,
      aux_sym_width_repeat1,
    STATE(42), 1,
      sym_grouping_option,
    STATE(63), 1,
      sym_type,
  [163] = 2,
    ACTIONS(33), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
    ACTIONS(47), 8,
      anon_sym_RBRACE,
      anon_sym_z,
      anon_sym_POUND,
      aux_sym_align_token1,
      aux_sym_align_token2,
      aux_sym_align_token3,
      aux_sym_align_token4,
      sym_precision,
  [180] = 2,
    ACTIONS(33), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
    ACTIONS(49), 7,
      anon_sym_RBRACE,
      anon_sym_z,
      anon_sym_POUND,
      aux_sym_align_token2,
      aux_sym_align_token3,
      aux_sym_align_token4,
      sym_precision,
  [196] = 4,
    ACTIONS(53), 1,
      anon_sym_DOT,
    ACTIONS(55), 1,
      aux_sym_align_token2,
    STATE(8), 1,
      aux_sym_width_repeat1,
    ACTIONS(51), 8,
      anon_sym_RBRACE,
      sym_conversion,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
      aux_sym_align_token3,
      aux_sym_align_token4,
      sym_precision,
  [216] = 11,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(31), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      aux_sym_align_token2,
    ACTIONS(37), 1,
      aux_sym_align_token3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(41), 1,
      sym_precision,
    ACTIONS(43), 1,
      anon_sym_z,
    STATE(25), 1,
      sym_width,
    STATE(26), 1,
      aux_sym_width_repeat1,
    STATE(42), 1,
      sym_grouping_option,
    STATE(63), 1,
      sym_type,
  [250] = 8,
    ACTIONS(58), 1,
      anon_sym_RBRACE,
    ACTIONS(60), 1,
      sym_conversion,
    ACTIONS(62), 1,
      anon_sym_COLON,
    ACTIONS(64), 1,
      aux_sym_align_token2,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(19), 1,
      aux_sym_width_repeat1,
    STATE(71), 1,
      sym_format_spec,
    STATE(28), 4,
      sym_attribute_expression,
      sym_item_expression,
      sym__expression,
      sym_integer,
  [278] = 11,
    ACTIONS(35), 1,
      aux_sym_align_token2,
    ACTIONS(37), 1,
      aux_sym_align_token3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    ACTIONS(70), 1,
      anon_sym_z,
    ACTIONS(72), 1,
      anon_sym_POUND,
    ACTIONS(74), 1,
      sym_precision,
    STATE(26), 1,
      aux_sym_width_repeat1,
    STATE(29), 1,
      sym_width,
    STATE(46), 1,
      sym_grouping_option,
    STATE(61), 1,
      sym_type,
  [312] = 10,
    ACTIONS(35), 1,
      aux_sym_align_token2,
    ACTIONS(37), 1,
      aux_sym_align_token3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    ACTIONS(72), 1,
      anon_sym_POUND,
    ACTIONS(74), 1,
      sym_precision,
    STATE(26), 1,
      aux_sym_width_repeat1,
    STATE(29), 1,
      sym_width,
    STATE(46), 1,
      sym_grouping_option,
    STATE(61), 1,
      sym_type,
  [343] = 10,
    ACTIONS(35), 1,
      aux_sym_align_token2,
    ACTIONS(37), 1,
      aux_sym_align_token3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(76), 1,
      anon_sym_RBRACE,
    ACTIONS(78), 1,
      anon_sym_POUND,
    ACTIONS(80), 1,
      sym_precision,
    STATE(26), 1,
      aux_sym_width_repeat1,
    STATE(27), 1,
      sym_width,
    STATE(48), 1,
      sym_grouping_option,
    STATE(65), 1,
      sym_type,
  [374] = 9,
    ACTIONS(35), 1,
      aux_sym_align_token2,
    ACTIONS(37), 1,
      aux_sym_align_token3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(76), 1,
      anon_sym_RBRACE,
    ACTIONS(80), 1,
      sym_precision,
    STATE(26), 1,
      aux_sym_width_repeat1,
    STATE(27), 1,
      sym_width,
    STATE(48), 1,
      sym_grouping_option,
    STATE(65), 1,
      sym_type,
  [402] = 9,
    ACTIONS(35), 1,
      aux_sym_align_token2,
    ACTIONS(37), 1,
      aux_sym_align_token3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    ACTIONS(74), 1,
      sym_precision,
    STATE(26), 1,
      aux_sym_width_repeat1,
    STATE(29), 1,
      sym_width,
    STATE(46), 1,
      sym_grouping_option,
    STATE(61), 1,
      sym_type,
  [430] = 9,
    ACTIONS(35), 1,
      aux_sym_align_token2,
    ACTIONS(37), 1,
      aux_sym_align_token3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    ACTIONS(84), 1,
      sym_precision,
    STATE(26), 1,
      aux_sym_width_repeat1,
    STATE(30), 1,
      sym_width,
    STATE(49), 1,
      sym_grouping_option,
    STATE(66), 1,
      sym_type,
  [458] = 2,
    ACTIONS(33), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
    ACTIONS(86), 5,
      anon_sym_RBRACE,
      aux_sym_align_token2,
      aux_sym_align_token3,
      aux_sym_align_token4,
      sym_precision,
  [472] = 1,
    ACTIONS(88), 8,
      anon_sym_RBRACE,
      anon_sym_z,
      anon_sym_POUND,
      aux_sym_align_token1,
      aux_sym_align_token2,
      aux_sym_align_token3,
      aux_sym_align_token4,
      sym_precision,
  [483] = 3,
    ACTIONS(92), 1,
      aux_sym_align_token2,
    STATE(8), 1,
      aux_sym_width_repeat1,
    ACTIONS(90), 6,
      anon_sym_RBRACE,
      sym_conversion,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COLON,
  [498] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    STATE(21), 2,
      sym_replacement,
      aux_sym_text_repeat1,
    ACTIONS(96), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [514] = 4,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    STATE(21), 2,
      sym_replacement,
      aux_sym_text_repeat1,
    ACTIONS(100), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [530] = 1,
    ACTIONS(49), 7,
      anon_sym_RBRACE,
      anon_sym_z,
      anon_sym_POUND,
      aux_sym_align_token2,
      aux_sym_align_token3,
      aux_sym_align_token4,
      sym_precision,
  [540] = 2,
    ACTIONS(106), 3,
      anon_sym_RBRACE,
      aux_sym_align_token4,
      sym_precision,
    ACTIONS(33), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
  [552] = 6,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(37), 1,
      aux_sym_align_token3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(41), 1,
      sym_precision,
    STATE(42), 1,
      sym_grouping_option,
    STATE(63), 1,
      sym_type,
  [571] = 6,
    ACTIONS(37), 1,
      aux_sym_align_token3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    ACTIONS(74), 1,
      sym_precision,
    STATE(46), 1,
      sym_grouping_option,
    STATE(61), 1,
      sym_type,
  [590] = 3,
    ACTIONS(92), 1,
      aux_sym_align_token2,
    STATE(8), 1,
      aux_sym_width_repeat1,
    ACTIONS(108), 4,
      anon_sym_RBRACE,
      aux_sym_align_token3,
      aux_sym_align_token4,
      sym_precision,
  [603] = 6,
    ACTIONS(37), 1,
      aux_sym_align_token3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    ACTIONS(84), 1,
      sym_precision,
    STATE(49), 1,
      sym_grouping_option,
    STATE(66), 1,
      sym_type,
  [622] = 6,
    ACTIONS(62), 1,
      anon_sym_COLON,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    ACTIONS(112), 1,
      sym_conversion,
    ACTIONS(114), 1,
      anon_sym_DOT,
    ACTIONS(116), 1,
      anon_sym_LBRACK,
    STATE(74), 1,
      sym_format_spec,
  [641] = 6,
    ACTIONS(37), 1,
      aux_sym_align_token3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(76), 1,
      anon_sym_RBRACE,
    ACTIONS(80), 1,
      sym_precision,
    STATE(48), 1,
      sym_grouping_option,
    STATE(65), 1,
      sym_type,
  [660] = 6,
    ACTIONS(37), 1,
      aux_sym_align_token3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    ACTIONS(120), 1,
      sym_precision,
    STATE(43), 1,
      sym_grouping_option,
    STATE(70), 1,
      sym_type,
  [679] = 2,
    ACTIONS(124), 1,
      anon_sym_LBRACE,
    ACTIONS(122), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [689] = 2,
    ACTIONS(128), 1,
      anon_sym_LBRACE,
    ACTIONS(126), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [699] = 2,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    ACTIONS(130), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [709] = 2,
    ACTIONS(136), 1,
      anon_sym_LBRACE,
    ACTIONS(134), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [719] = 2,
    ACTIONS(140), 1,
      anon_sym_LBRACE,
    ACTIONS(138), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [729] = 2,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
    ACTIONS(33), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
  [739] = 1,
    ACTIONS(144), 5,
      anon_sym_RBRACE,
      sym_conversion,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_COLON,
  [747] = 2,
    ACTIONS(148), 1,
      anon_sym_LBRACE,
    ACTIONS(146), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [757] = 1,
    ACTIONS(150), 5,
      anon_sym_RBRACE,
      sym_conversion,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_COLON,
  [765] = 2,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(152), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [775] = 2,
    ACTIONS(158), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      aux_sym_text_token1,
  [785] = 4,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    ACTIONS(74), 1,
      sym_precision,
    STATE(61), 1,
      sym_type,
  [798] = 4,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    ACTIONS(162), 1,
      sym_precision,
    STATE(73), 1,
      sym_type,
  [811] = 1,
    ACTIONS(33), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_EQ,
      anon_sym_CARET,
  [818] = 4,
    ACTIONS(164), 1,
      aux_sym_align_token2,
    ACTIONS(166), 1,
      sym_item_string,
    STATE(19), 1,
      aux_sym_width_repeat1,
    STATE(72), 1,
      sym_integer,
  [831] = 4,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(76), 1,
      anon_sym_RBRACE,
    ACTIONS(80), 1,
      sym_precision,
    STATE(65), 1,
      sym_type,
  [844] = 4,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(41), 1,
      sym_precision,
    STATE(63), 1,
      sym_type,
  [857] = 4,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    ACTIONS(84), 1,
      sym_precision,
    STATE(66), 1,
      sym_type,
  [870] = 4,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    ACTIONS(120), 1,
      sym_precision,
    STATE(70), 1,
      sym_type,
  [883] = 3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    STATE(73), 1,
      sym_type,
  [893] = 3,
    ACTIONS(62), 1,
      anon_sym_COLON,
    ACTIONS(168), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      sym_format_spec,
  [903] = 3,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    STATE(63), 1,
      sym_type,
  [913] = 3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(76), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      sym_type,
  [923] = 3,
    ACTIONS(62), 1,
      anon_sym_COLON,
    ACTIONS(170), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      sym_format_spec,
  [933] = 1,
    ACTIONS(106), 3,
      anon_sym_RBRACE,
      aux_sym_align_token4,
      sym_precision,
  [939] = 3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      sym_type,
  [949] = 3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym_type,
  [959] = 3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      sym_type,
  [969] = 3,
    ACTIONS(39), 1,
      aux_sym_align_token4,
    ACTIONS(172), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      sym_type,
  [979] = 1,
    ACTIONS(174), 1,
      anon_sym_RBRACE,
  [983] = 1,
    ACTIONS(76), 1,
      anon_sym_RBRACE,
  [987] = 1,
    ACTIONS(176), 1,
      ts_builtin_sym_end,
  [991] = 1,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
  [995] = 1,
    ACTIONS(178), 1,
      sym_identifier,
  [999] = 1,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
  [1003] = 1,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
  [1007] = 1,
    ACTIONS(180), 1,
      anon_sym_RBRACE,
  [1011] = 1,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
  [1015] = 1,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
  [1019] = 1,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
  [1023] = 1,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
  [1027] = 1,
    ACTIONS(184), 1,
      anon_sym_RBRACK,
  [1031] = 1,
    ACTIONS(172), 1,
      anon_sym_RBRACE,
  [1035] = 1,
    ACTIONS(186), 1,
      anon_sym_RBRACE,
  [1039] = 1,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 52,
  [SMALL_STATE(4)] = 89,
  [SMALL_STATE(5)] = 123,
  [SMALL_STATE(6)] = 163,
  [SMALL_STATE(7)] = 180,
  [SMALL_STATE(8)] = 196,
  [SMALL_STATE(9)] = 216,
  [SMALL_STATE(10)] = 250,
  [SMALL_STATE(11)] = 278,
  [SMALL_STATE(12)] = 312,
  [SMALL_STATE(13)] = 343,
  [SMALL_STATE(14)] = 374,
  [SMALL_STATE(15)] = 402,
  [SMALL_STATE(16)] = 430,
  [SMALL_STATE(17)] = 458,
  [SMALL_STATE(18)] = 472,
  [SMALL_STATE(19)] = 483,
  [SMALL_STATE(20)] = 498,
  [SMALL_STATE(21)] = 514,
  [SMALL_STATE(22)] = 530,
  [SMALL_STATE(23)] = 540,
  [SMALL_STATE(24)] = 552,
  [SMALL_STATE(25)] = 571,
  [SMALL_STATE(26)] = 590,
  [SMALL_STATE(27)] = 603,
  [SMALL_STATE(28)] = 622,
  [SMALL_STATE(29)] = 641,
  [SMALL_STATE(30)] = 660,
  [SMALL_STATE(31)] = 679,
  [SMALL_STATE(32)] = 689,
  [SMALL_STATE(33)] = 699,
  [SMALL_STATE(34)] = 709,
  [SMALL_STATE(35)] = 719,
  [SMALL_STATE(36)] = 729,
  [SMALL_STATE(37)] = 739,
  [SMALL_STATE(38)] = 747,
  [SMALL_STATE(39)] = 757,
  [SMALL_STATE(40)] = 765,
  [SMALL_STATE(41)] = 775,
  [SMALL_STATE(42)] = 785,
  [SMALL_STATE(43)] = 798,
  [SMALL_STATE(44)] = 811,
  [SMALL_STATE(45)] = 818,
  [SMALL_STATE(46)] = 831,
  [SMALL_STATE(47)] = 844,
  [SMALL_STATE(48)] = 857,
  [SMALL_STATE(49)] = 870,
  [SMALL_STATE(50)] = 883,
  [SMALL_STATE(51)] = 893,
  [SMALL_STATE(52)] = 903,
  [SMALL_STATE(53)] = 913,
  [SMALL_STATE(54)] = 923,
  [SMALL_STATE(55)] = 933,
  [SMALL_STATE(56)] = 939,
  [SMALL_STATE(57)] = 949,
  [SMALL_STATE(58)] = 959,
  [SMALL_STATE(59)] = 969,
  [SMALL_STATE(60)] = 979,
  [SMALL_STATE(61)] = 983,
  [SMALL_STATE(62)] = 987,
  [SMALL_STATE(63)] = 991,
  [SMALL_STATE(64)] = 995,
  [SMALL_STATE(65)] = 999,
  [SMALL_STATE(66)] = 1003,
  [SMALL_STATE(67)] = 1007,
  [SMALL_STATE(68)] = 1011,
  [SMALL_STATE(69)] = 1015,
  [SMALL_STATE(70)] = 1019,
  [SMALL_STATE(71)] = 1023,
  [SMALL_STATE(72)] = 1027,
  [SMALL_STATE(73)] = 1031,
  [SMALL_STATE(74)] = 1035,
  [SMALL_STATE(75)] = 1039,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_align, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sign, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_width_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_width_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_width_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 4, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 5, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_width_repeat1, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_align, 2, 0, 5),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouping_option, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_width, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 6, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replacement, 3, 0, 3),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replacement, 3, 0, 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replacement, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replacement, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replacement, 3, 0, 1),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replacement, 3, 0, 1),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replacement, 4, 0, 4),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replacement, 4, 0, 4),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replacement, 3, 0, 2),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replacement, 3, 0, 2),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_expression, 3, 0, 7),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replacement, 5, 0, 9),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replacement, 5, 0, 9),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_expression, 4, 0, 10),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replacement, 4, 0, 6),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replacement, 4, 0, 6),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replacement, 4, 0, 8),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replacement, 4, 0, 8),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 7, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 8, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [176] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 9, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_format_string(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
